nova_state/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path

from . import views

urlpatterns = [
    path('nova-admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('properties/', include('properties.urls')),
]

properties/urls.py
from django.urls import include, path

from . import views

app_name = 'properties'

urlpatterns = [
    path('<str:property_id>/', views.get_property, name='get_property'),
    path('<str:property_id>/post-contact/', views.post_contact, name='post_contact'),
]

properties/models.py
from django.db import models

# Create your models here.

nova_state/views.py
import json

import requests
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse

from local_modules.easybroker_conn import EasyBrokerConnection



def index(request):
	"""Get properties and render the main page."""
	properties_are_cached = ('properties' in request.session) # Check if there is information about the properties in the session cache
	successful_connection = True

	if not properties_are_cached or request.session['properties'] is None:
		easybroker_conn = EasyBrokerConnection()
		request.session['properties'] = easybroker_conn.get_properties()
		successful_connection = (easybroker_conn.status_code == 200)
	
	data = request.session['properties']

	properties_per_page = 15
	page = request.GET.get('page', 1)
	paginator = Paginator(data, properties_per_page)

	try:
		properties = paginator.page(page)
	except PageNotAnInteger:
		properties = paginator.page(1)
	except EmptyPage:
		properties = paginator.page(paginator.num_pages)
	
	return render(request, 'index.html', { 'properties': properties })


def login_view(request):
	"""Redirect to the main page once the session is re-established."""	
	return redirect('index')

properties/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from local_modules.easybroker_conn import EasyBrokerConnection



def get_property(request, property_id):
	"""Get a specific property and render the property page."""
	easybroker_conn = EasyBrokerConnection()
	prop = easybroker_conn.get_property(property_id)

	# Property not found or no longer available
	if easybroker_conn.status_code != 200:
		return redirect('index')

	return render(request, 'properties/property.html', {
		'property': prop
	})


def post_contact(request, property_id):
	"""Create or update a new lead for the property."""
	easybroker_conn = EasyBrokerConnection()
	easybroker_conn.post_contact(
		name=request.POST['name'], phone=request.POST['phone'],
		email=request.POST['email'], property_id=property_id,
		message=request.POST['message'], source='novastate.com'
	)

	if easybroker_conn.status_code == 200:
		messages.success(request, "Lead created successfully.")
	else: # Property not found or no longer available
		messages.error(request, "Could not create lead.")

	return redirect('properties:get_property', property_id=property_id)

templates/index.html
{% extends 'layout.html' %}

{% block title %}Home{% endblock %}

{% load static %}

{% block body %}

	<!-- Navigation
		---------------------------------------------->

		{% include "nav.html" %}

	<!-- Header
		---------------------------------------------->

	<header id="header">
		<div class="intro" style="background: url({% static 'img/intro-bg.jpg' %}) center center no-repeat">
			<div class="overlay">
				<div class="container">
					<div class="row">
						<div class="col-md-8 col-md-offset-2 intro-text">
							<h1>Home Management<br>
							& Sales</h1>
							<p>We are Nova Estate, a company specializing in property purchase and rental management, driven by providing the best advice to clients on the technical conditions of their processes and operations.</p>
							<a href="#home" class="btn btn-custom btn-lg page-scroll">Learn More</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</header>
	
	<!-- Home Section
		---------------------------------------------->

	<div id="home">
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-md-6"><img src="{% static 'img/about.jpg' %}" class="img-responsive" alt=""></div>
				<div class="col-xs-12 col-md-6">
					<div class="home-text">
						<h2>Who We Are</h2>
						<p>We have the best-trained people in the industry, motivated to provide excellent customer service, offering objective, quality, and well-detailed advice on the entire process of buying and selling real estate.</p>
						<h3>Why Choose Us?</h3>
						<div class="list-style">
							<div class="col-lg-6 col-sm-6 col-xs-12">
								<ul>
									<li>Years of Experience</li>
									<li>Fully Insured</li>
									<li>Cost Control Experts</li>
									<li>100% Satisfaction Guarantee</li>
								</ul>
							</div>
							<div class="col-lg-6 col-sm-6 col-xs-12">
								<ul>
									<li>Free Consultation</li>
									<li>Satisfied Customers</li>
									<li>Project Management</li>
									<li>Affordable Pricing</li>
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Properties Section
		---------------------------------------------->

	<div id="properties">
		<div class="container">
			<div class="section-title">
				<h2>Properties</h2>
			</div>


			<!--
			{'public_id': 'EB-C6667', 'title': 'DEPARTAMENTO EN RENTA EN BOSQUES DEL VALLE EN SAN PEDRO GARZA GARCIA', 'title_image_full': None, 'title_image_thumb': None, 'location': 'Zona Bosques del Valle, San Pedro Garza García, Nuevo León', 'operations': [{'type': 'rental', 'amount': 110000.0, 'currency': 'MXN', 'formatted_amount': '$110,000', 'commission': {'type': 'percentage'}, 'unit': 'total'}], 'bedrooms': 3, 'bathrooms': None, 'parking_spaces': 4, 'property_type': 'Departamento', 'lot_size': 0.0, 'construction_size': 538.0, 'updated_at': '2022-08-07T14:25:34-05:00', 'agent': None, 'show_prices': True, 'share_commission': False},

			{'public_id': 'EB-C6550', 'title': 'CASA EN RENTA EN FUENTES DEL VALLE EN SAN PEDRO GARZA GARCÍA', 'title_image_full': 'https://assets.stagingeb.com/property_images/36550/127846/EB-C6550.jpg?version=1611968798', 'title_image_thumb': 'https://assets.stagingeb.com/property_images/36550/127846/EB-C6550_thumb.jpg?version=1611968798', 'location': 'Fuentes del Valle, San Pedro Garza García, Nuevo León', 'operations': [{'type': 'rental', 'amount': 39000.0, 'currency': 'MXN', 'formatted_amount': '$39,000', 'commission': {'type': 'percentage'}, 'unit': 'total'}], 'bedrooms': 3, 'bathrooms': 1, 'parking_spaces': 2, 'property_type': 'Casa', 'lot_size': 250.0, 'construction_size': 450.0, 'updated_at': '2022-08-07T14:25:35-05:00', 'agent': None, 'show_prices': True, 'share_commission': False},


			-->

			<div class="row">
				{% for property in properties %}
					<div class="col-md-4 property-container">
						<a href="{% url 'properties:get_property' property.public_id %}">
							<div class="propertie-media"><img class="hover-bg" src="{{ property.title_image_thumb }}" alt=""></div>
							<div class="propertie-desc">
								<h5>{{ property.public_id }}</h5>
								<h3>{{ property.title }}</h3>
								<p>{{ property.property_type }} - {{ property.location }}</p>
							</div>
						</a>
					</div>
				{% endfor %}
			</div>

			{% if properties.has_other_pages %}
				<div class="text-center">
					<ul class="pagination pagination-sm">

						{% if properties.has_previous %}
							<li><a href="?page={{ properties.previous_page_number }}#properties">Previous</a></li>
						{% else %}
							<li class="disabled"><span>Previous</span></li>
						{% endif %}

						{% for i in properties.paginator.page_range %}
							{% if properties.number == i %}
								<li class="list-inline active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
							{% else %}
								<li class="list-inline"><a href="?page={{ i }}#properties">{{ i }}</a></li>
							{% endif %}
						{% endfor %}

						{% if properties.has_next %}
							<li><a href="?page={{ properties.next_page_number }}#properties">Next</a></li>
						{% else %}
							<li class="disabled"><span>Next</span></li>
						{% endif %}

					</ul>
				</div>
			{% endif %}

		</div>
	</div>



	<!-- Contact Section
		---------------------------------------------->

	<!--
	<div id="contact">
	<div class="container">
	<div class="col-md-8">
	<div class="row">
	<div class="section-title">
	<h2>Get In Touch</h2>
	<p>Please fill out the form below to send us an email and we will get back to you as soon as possible.</p>
	</div>
	<form name="sentMessage" id="contactForm" novalidate>
	<div class="row">
	<div class="col-md-6">
	<div class="form-group">
	<input type="text" id="name" class="form-control" placeholder="Name" required="required">
	<p class="help-block text-danger"></p>
	</div>
	</div>
	<div class="col-md-6">
	<div class="form-group">
	<input type="email" id="email" class="form-control" placeholder="Email" required="required">
	<p class="help-block text-danger"></p>
	</div>
	</div>
	</div>
	<div class="form-group">
	<textarea name="message" id="message" class="form-control" rows="4" placeholder="Message" required></textarea>
	<p class="help-block text-danger"></p>
	</div>
	<div id="success"></div>
	<button type="submit" class="btn btn-custom btn-lg">Send Message</button>
	</form>
	</div>
	</div>
	<div class="col-md-3 col-md-offset-1 contact-info">
	<div class="contact-item">
	<h4>Contact Info</h4>
	<p><span>Address</span>4321 California St,<br>
	San Francisco, CA 12345</p>
	</div>
	<div class="contact-item">
	<p><span>Phone</span> +1 123 456 1234</p>
	</div>
	<div class="contact-item">
	<p><span>Email</span> info@company.com</p>
	</div>
	</div>
	<div class="col-md-12">
	<div class="row">
	<div class="social">
	<ul>
	<li><a href="#"><i class="fa fa-facebook"></i></a></li>
	<li><a href="#"><i class="fa fa-twitter"></i></a></li>
	<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
	<li><a href="#"><i class="fa fa-youtube"></i></a></li>
	</ul>
	</div>
	</div>
	</div>
	</div>
	</div>
	-->

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="">
		<meta name="author" content="">
		<title>{% block title %}{% endblock %} | Nova State</title>
		
		{% load static %}

		<!-- Favicons
			---------------------------------------------->

		<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
		<link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">
		<link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/apple-touch-icon-72x72.png' %}">
		<link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/apple-touch-icon-114x114.png' %}">

		<!-- Bootstrap
			---------------------------------------------->
		
		<link rel="stylesheet" type="text/css"  href="{% static 'css/bootstrap.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">

		<!-- Stylesheet
			---------------------------------------------->

		<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/nivo-lightbox/nivo-lightbox.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/nivo-lightbox/default.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		    <![endif]-->

	</head>
	<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

		<!-- Body
			---------------------------------------------->

		{% block body %}{% endblock %}

		<!-- Footer Section
			---------------------------------------------->

		<div id="footer">
			<div class="container text-center">
				<p>&copy; 2022 NOVA STATE All Rights Reserved.<p>
				<p>Design by <a href="http://www.templatewire.com" rel="nofollow">TemplateWire</a></p>
			</div>
		</div>
		<script type="text/javascript" src="{% static 'js/jquery.1.11.1.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script> 
		<script type="text/javascript" src="{% static 'js/SmoothScroll.js' %}"></script> 
		<script type="text/javascript" src="{% static 'js/nivo-lightbox.js' %}"></script> 
		<script type="text/javascript" src="{% static 'js/jqBootstrapValidation.js' %}"></script> 
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
	</body>
</html>

templates/nav.html
<nav id="menu" class="navbar navbar-default navbar-fixed-top">
	<div class="container"> 
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand page-scroll" href="#page-top">Nova State</a>
		<div class="phone"><span>Call Today</span>221-247-8747</div>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav navbar-right">
			<li><a href="#home" class="page-scroll">Home</a></li>
			<li><a href="#properties" class="page-scroll">Properties</a></li>
		</ul>
	</div>
	<!-- /.navbar-collapse --> 
	</div>
</nav>

templates/properties/nav.html
<nav id="menu" class="navbar navbar-default navbar-fixed-top">
	<div class="container"> 
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand page-scroll" href="#page-top">Nova State</a>
		<div class="phone"><span>Call Today</span>221-247-8747</div>
	</div>

	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		<ul class="nav navbar-nav navbar-right">
			<li><a href="{% url 'index' %}" class="page-scroll">Home</a></li>
			<li><a href="#property-home" class="page-scroll">Info</a></li>
			<li><a href="#gallery" class="page-scroll">Gallery</a></li>
			<li><a href="#new_lead" class="page-scroll">New Lead</a></li>
		</ul>
	</div>
	<!-- /.navbar-collapse --> 
	</div>
</nav>

templates/properties/property.html
{% extends 'layout.html' %}

{% block title %}{{ property.public_id }}{% endblock %}

{% load static %}

{% block body %}

	<!-- Navigation
		---------------------------------------------->

		{% include "properties/nav.html" %}

	<!-- Header
		---------------------------------------------->

	<header id="header">
		<a href="{{ property.property_images.0.url }}">
			<div class="intro" style="background: url({{ property.property_images.0.url }}) center center no-repeat">
				<div class="overlay">
					<div class="container">
						<div class="row">
							<div class="col-md-8 col-md-offset-2 intro-text">
								<h1>{{ property.title }}</h1>
							</div>
						</div>
					</div>
				</div>
			</div>
		</a>
	</header>

	<!-- Home Section
		---------------------------------------------->

	<div id="property-home">
		<div class="container">
				<div class="home-text">
					<h2>{{ property.public_id }}</h2>
					<h5>{{ property.property_type }}</h5>
					<h3>{{ property.location.name}}</h3>
					<p>{{ property.description }}</p>
				</div>
		</div>
	</div>

	<!-- Gallery Section
		---------------------------------------------->

	<div id="gallery">
		<div class="container">
			<div class="section-title">
				<h2>Gallery</h2>
			</div>
			<div class="row">
				<div class="gallery-items">
					{% for img in property.property_images %}
						<div class="col-sm-6 col-md-4 col-lg-4">
							<div class="gallery-item">
								<div class="hover-bg">
									<a href="{{ img.url }}" title="Project Title" data-lightbox-gallery="gallery1">
										<div class="hover-text">
											<h4>{{ img.title }}</h4>
										</div>
										<img src="{{ img.url }}" class="img-responsive" alt="Project Title">
									</a>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</div>

	<!-- Contact Section
		---------------------------------------------->
	
	<div id="new_lead">
		<div class="container">
			<div class="section-title">
				<h2>New Lead</h2>
				<p>Fill out the form below to create a new lead for the property</p>
			</div>
			<div class="form-group">
				<form action="{% url 'properties:post_contact' property.public_id %}" method="post">
					{% csrf_token %}
					<div class="row">
						<div class="col-md-6">
							<div class="form-group">
								<input name="name" type="text" id="name" class="form-control" placeholder="Name" required="required">
								<p class="help-block text-danger"></p>
							</div>
						</div>
						<div class="col-md-6">
							<div class="form-group">
								<input name="phone" type="tel" id="phone" class="form-control" placeholder="Phone" required="required">
								<p class="help-block text-danger"></p>
							</div>
						</div>
					</div>
					<div class="form-group">
						<input name="email" type="email" id="email" class="form-control" placeholder="Email" required="required">
						<p class="help-block text-danger"></p>
					</div>
					<div class="form-group">
						<textarea name="message" id="message" class="form-control" rows="4" placeholder="Message" required></textarea>
						<p class="help-block text-danger"></p>
					</div>
					<div id="success"></div>
					<button type="submit" class="btn btn-custom btn-lg">Submit</button>
				</form>
			</div>
		</div>
	</div>

{% endblock %}